name: "Export Obsidian vault to HTML"
description: "Exports the Obsidian vault to HTML using a Docker container"

inputs:
  vault:
    description: "Path to the Obsidian vault"
    required: true
    default: "."
  config:
    description: "Path to the configuration file"
    required: false
  version:
    description: "Version of the plugin"
    required: false
    default: "latest"

outputs:
  output:
    description: "Path to the output folder"
    value: ${{ steps.run-docker.outputs.output }}

runs:
  using: "composite"
  steps:
    - name: Run docker container
      id: run-docker
      shell: bash
      run: |
        mkdir -p ./.output

        if [ -z "${{ inputs.config }}" ]; then
          docker run --rm \
            -v "${{ inputs.vault }}:/vault" \
            -v "${{ github.workspace }}/.output:/output" \
            ghcr.io/kosmosisdire/obsidian-webpage-export:${{ inputs.version }} >> ./.log.txt
        else
          docker run --rm \
            -v "${{ inputs.vault }}:/vault" \
            -v "${{ inputs.config }}:/config.json" \
            -v "${{ github.workspace }}/.output:/output" \
            ghcr.io/kosmosisdire/obsidian-webpage-export:${{ inputs.version }} >> ./.log.txt
        fi

        echo "output=${{ github.workspace }}/.output" >> $GITHUB_OUTPUT
